### ISSUE TITLE
Make project buildable

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/zond#1]

**Comment by 0pdd** [comment]
@DronMDF 2 puzzles [#3](https://github.com/DronMDF/zond/issues/3), [#4](https://github.com/DronMDF/zond/issues/4) are still not solved.

**Comment by 0pdd** [comment]
@DronMDF the puzzle [#4](https://github.com/DronMDF/zond/issues/4) is still not solved; solved: [#3](https://github.com/DronMDF/zond/issues/3).

**Comment by 0pdd** [comment]
@DronMDF all 2 puzzles are solved here: [#3](https://github.com/DronMDF/zond/issues/3), [#4](https://github.com/DronMDF/zond/issues/4).
