### ISSUE TITLE
ZoldProtocolEntry implementation

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/zond#105]
At first this class should be set Zold-Score in Response header

**Comment by 0pdd** [comment]
@DronMDF 3 puzzles [#108](https://github.com/DronMDF/zond/issues/108), [#109](https://github.com/DronMDF/zond/issues/109), [#110](https://github.com/DronMDF/zond/issues/110) are still not solved.

**Comment by 0pdd** [comment]
@DronMDF 2 puzzles [#109](https://github.com/DronMDF/zond/issues/109), [#110](https://github.com/DronMDF/zond/issues/110) are still not solved; solved: [#108](https://github.com/DronMDF/zond/issues/108).

**Comment by 0pdd** [comment]
@DronMDF the puzzle [#110](https://github.com/DronMDF/zond/issues/110) is still not solved; solved: [#108](https://github.com/DronMDF/zond/issues/108), [#109](https://github.com/DronMDF/zond/issues/109).

**Comment by 0pdd** [comment]
@DronMDF all 3 puzzles are solved here: [#108](https://github.com/DronMDF/zond/issues/108), [#109](https://github.com/DronMDF/zond/issues/109), [#110](https://github.com/DronMDF/zond/issues/110).
