### ISSUE TITLE
ZoldProtocolEntry should set X-Zold-Score to 

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/zond#111]
??? X-Zold-Path: http://138.197.140.42:4096/remotes
X-Zold-Version: 0.18.8
X-Zold-Repo: zold-io/zold
X-Zold-Protocol: 2
X-Zold-Score: 8 5c158399 138.197.140.42 1000 jqnML5Er 912ecc24b32dbe74 KJt3rE X3kb0z BYHOy0 KhF5Ie
??? X-Zold-Thread: 27365320
??? X-Zold-Milliseconds: 1

Need to set all nonquestion headers

**Comment by 0pdd** [comment]
@DronMDF 2 puzzles [#117](https://github.com/DronMDF/zond/issues/117), [#118](https://github.com/DronMDF/zond/issues/118) are still not solved.

**Comment by 0pdd** [comment]
@DronMDF 3 puzzles [#117](https://github.com/DronMDF/zond/issues/117), [#123](https://github.com/DronMDF/zond/issues/123), [#124](https://github.com/DronMDF/zond/issues/124) are still not solved; solved: [#118](https://github.com/DronMDF/zond/issues/118).

**Comment by 0pdd** [comment]
@DronMDF 3 puzzles [#117](https://github.com/DronMDF/zond/issues/117), [#124](https://github.com/DronMDF/zond/issues/124), [#126](https://github.com/DronMDF/zond/issues/126) are still not solved; solved: [#118](https://github.com/DronMDF/zond/issues/118), [#123](https://github.com/DronMDF/zond/issues/123).

**Comment by 0pdd** [comment]
@DronMDF 3 puzzles [#117](https://github.com/DronMDF/zond/issues/117), [#126](https://github.com/DronMDF/zond/issues/126), [#133](https://github.com/DronMDF/zond/issues/133) are still not solved; solved: [#118](https://github.com/DronMDF/zond/issues/118), [#123](https://github.com/DronMDF/zond/issues/123), [#124](https://github.com/DronMDF/zond/issues/124), [#128](https://github.com/DronMDF/zond/issues/128).

**Comment by 0pdd** [comment]
@DronMDF 3 puzzles [#117](https://github.com/DronMDF/zond/issues/117), [#133](https://github.com/DronMDF/zond/issues/133), [#138](https://github.com/DronMDF/zond/issues/138) are still not solved; solved: [#118](https://github.com/DronMDF/zond/issues/118), [#123](https://github.com/DronMDF/zond/issues/123), [#124](https://github.com/DronMDF/zond/issues/124), [#126](https://github.com/DronMDF/zond/issues/126), [#128](https://github.com/DronMDF/zond/issues/128).

**Comment by 0pdd** [comment]
@DronMDF 5 puzzles [#133](https://github.com/DronMDF/zond/issues/133), [#138](https://github.com/DronMDF/zond/issues/138), [#145](https://github.com/DronMDF/zond/issues/145), [#146](https://github.com/DronMDF/zond/issues/146), [#147](https://github.com/DronMDF/zond/issues/147) are still not solved; solved: [#117](https://github.com/DronMDF/zond/issues/117), [#118](https://github.com/DronMDF/zond/issues/118), [#123](https://github.com/DronMDF/zond/issues/123), [#124](https://github.com/DronMDF/zond/issues/124), [#126](https://github.com/DronMDF/zond/issues/126), [#128](https://github.com/DronMDF/zond/issues/128).

**Comment by 0pdd** [comment]
@DronMDF 4 puzzles [#133](https://github.com/DronMDF/zond/issues/133), [#145](https://github.com/DronMDF/zond/issues/145), [#146](https://github.com/DronMDF/zond/issues/146), [#147](https://github.com/DronMDF/zond/issues/147) are still not solved; solved: [#117](https://github.com/DronMDF/zond/issues/117), [#118](https://github.com/DronMDF/zond/issues/118), [#123](https://github.com/DronMDF/zond/issues/123), [#124](https://github.com/DronMDF/zond/issues/124), [#126](https://github.com/DronMDF/zond/issues/126), [#128](https://github.com/DronMDF/zond/issues/128), [#138](https://github.com/DronMDF/zond/issues/138).
