### ISSUE TITLE
Fix copyright year to 2018-19

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/zond#134]

**Comment by 0pdd** [comment]
@DronMDF the puzzle [#136](https://github.com/DronMDF/zond/issues/136) is still not solved.

**Comment by 0pdd** [comment]
@DronMDF 2 puzzles [#136](https://github.com/DronMDF/zond/issues/136), [#139](https://github.com/DronMDF/zond/issues/139) are still not solved.

**Comment by 0pdd** [comment]
@DronMDF 3 puzzles [#139](https://github.com/DronMDF/zond/issues/139), [#141](https://github.com/DronMDF/zond/issues/141), [#142](https://github.com/DronMDF/zond/issues/142) are still not solved; solved: [#136](https://github.com/DronMDF/zond/issues/136).

**Comment by 0pdd** [comment]
@DronMDF 4 puzzles [#139](https://github.com/DronMDF/zond/issues/139), [#141](https://github.com/DronMDF/zond/issues/141), [#151](https://github.com/DronMDF/zond/issues/151), [#152](https://github.com/DronMDF/zond/issues/152) are still not solved; solved: [#136](https://github.com/DronMDF/zond/issues/136), [#142](https://github.com/DronMDF/zond/issues/142).

**Comment by 0pdd** [comment]
@DronMDF 3 puzzles [#139](https://github.com/DronMDF/zond/issues/139), [#141](https://github.com/DronMDF/zond/issues/141), [#152](https://github.com/DronMDF/zond/issues/152) are still not solved; solved: [#136](https://github.com/DronMDF/zond/issues/136), [#142](https://github.com/DronMDF/zond/issues/142), [#151](https://github.com/DronMDF/zond/issues/151).

**Comment by 0pdd** [comment]
@DronMDF 3 puzzles [#139](https://github.com/DronMDF/zond/issues/139), [#141](https://github.com/DronMDF/zond/issues/141), [#156](https://github.com/DronMDF/zond/issues/156) are still not solved; solved: [#136](https://github.com/DronMDF/zond/issues/136), [#142](https://github.com/DronMDF/zond/issues/142), [#151](https://github.com/DronMDF/zond/issues/151), [#152](https://github.com/DronMDF/zond/issues/152).

**Comment by 0pdd** [comment]
@DronMDF 3 puzzles [#139](https://github.com/DronMDF/zond/issues/139), [#141](https://github.com/DronMDF/zond/issues/141), [#159](https://github.com/DronMDF/zond/issues/159) are still not solved; solved: [#136](https://github.com/DronMDF/zond/issues/136), [#142](https://github.com/DronMDF/zond/issues/142), [#151](https://github.com/DronMDF/zond/issues/151), [#152](https://github.com/DronMDF/zond/issues/152), [#156](https://github.com/DronMDF/zond/issues/156).

**Comment by 0pdd** [comment]
@DronMDF 4 puzzles [#139](https://github.com/DronMDF/zond/issues/139), [#159](https://github.com/DronMDF/zond/issues/159), [#169](https://github.com/DronMDF/zond/issues/169), [#170](https://github.com/DronMDF/zond/issues/170) are still not solved; solved: [#136](https://github.com/DronMDF/zond/issues/136), [#141](https://github.com/DronMDF/zond/issues/141), [#142](https://github.com/DronMDF/zond/issues/142), [#151](https://github.com/DronMDF/zond/issues/151), [#152](https://github.com/DronMDF/zond/issues/152), [#156](https://github.com/DronMDF/zond/issues/156).

**Comment by 0pdd** [comment]
@DronMDF 5 puzzles [#139](https://github.com/DronMDF/zond/issues/139), [#159](https://github.com/DronMDF/zond/issues/159), [#169](https://github.com/DronMDF/zond/issues/169), [#172](https://github.com/DronMDF/zond/issues/172), [#173](https://github.com/DronMDF/zond/issues/173) are still not solved; solved: [#136](https://github.com/DronMDF/zond/issues/136), [#141](https://github.com/DronMDF/zond/issues/141), [#142](https://github.com/DronMDF/zond/issues/142), [#151](https://github.com/DronMDF/zond/issues/151), [#152](https://github.com/DronMDF/zond/issues/152), [#156](https://github.com/DronMDF/zond/issues/156), [#170](https://github.com/DronMDF/zond/issues/170).

**Comment by 0pdd** [comment]
@DronMDF 5 puzzles [#139](https://github.com/DronMDF/zond/issues/139), [#159](https://github.com/DronMDF/zond/issues/159), [#169](https://github.com/DronMDF/zond/issues/169), [#173](https://github.com/DronMDF/zond/issues/173), [#176](https://github.com/DronMDF/zond/issues/176) are still not solved; solved: [#136](https://github.com/DronMDF/zond/issues/136), [#141](https://github.com/DronMDF/zond/issues/141), [#142](https://github.com/DronMDF/zond/issues/142), [#151](https://github.com/DronMDF/zond/issues/151), [#152](https://github.com/DronMDF/zond/issues/152), [#156](https://github.com/DronMDF/zond/issues/156), [#170](https://github.com/DronMDF/zond/issues/170), [#172](https://github.com/DronMDF/zond/issues/172).

**Comment by 0pdd** [comment]
@DronMDF 4 puzzles [#139](https://github.com/DronMDF/zond/issues/139), [#159](https://github.com/DronMDF/zond/issues/159), [#173](https://github.com/DronMDF/zond/issues/173), [#176](https://github.com/DronMDF/zond/issues/176) are still not solved; solved: [#136](https://github.com/DronMDF/zond/issues/136), [#141](https://github.com/DronMDF/zond/issues/141), [#142](https://github.com/DronMDF/zond/issues/142), [#151](https://github.com/DronMDF/zond/issues/151), [#152](https://github.com/DronMDF/zond/issues/152), [#156](https://github.com/DronMDF/zond/issues/156), [#169](https://github.com/DronMDF/zond/issues/169), [#170](https://github.com/DronMDF/zond/issues/170), [#172](https://github.com/DronMDF/zond/issues/172).

**Comment by 0pdd** [comment]
@DronMDF 3 puzzles [#139](https://github.com/DronMDF/zond/issues/139), [#159](https://github.com/DronMDF/zond/issues/159), [#176](https://github.com/DronMDF/zond/issues/176) are still not solved; solved: [#136](https://github.com/DronMDF/zond/issues/136), [#141](https://github.com/DronMDF/zond/issues/141), [#142](https://github.com/DronMDF/zond/issues/142), [#151](https://github.com/DronMDF/zond/issues/151), [#152](https://github.com/DronMDF/zond/issues/152), [#156](https://github.com/DronMDF/zond/issues/156), [#169](https://github.com/DronMDF/zond/issues/169), [#170](https://github.com/DronMDF/zond/issues/170), [#172](https://github.com/DronMDF/zond/issues/172), [#173](https://github.com/DronMDF/zond/issues/173).

**Comment by 0pdd** [comment]
@DronMDF 2 puzzles [#159](https://github.com/DronMDF/zond/issues/159), [#176](https://github.com/DronMDF/zond/issues/176) are still not solved; solved: [#136](https://github.com/DronMDF/zond/issues/136), [#139](https://github.com/DronMDF/zond/issues/139), [#141](https://github.com/DronMDF/zond/issues/141), [#142](https://github.com/DronMDF/zond/issues/142), [#151](https://github.com/DronMDF/zond/issues/151), [#152](https://github.com/DronMDF/zond/issues/152), [#156](https://github.com/DronMDF/zond/issues/156), [#169](https://github.com/DronMDF/zond/issues/169), [#170](https://github.com/DronMDF/zond/issues/170), [#172](https://github.com/DronMDF/zond/issues/172), [#173](https://github.com/DronMDF/zond/issues/173).
