### ISSUE TITLE
Using asio for server impl.

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/zond#15]
asio provide base io, http we should mase youself.

http scope is not big for this application

restino (https://habr.com/post/345788/) is very templated...

**Comment by 0pdd** [comment]
@DronMDF 4 puzzles [#17](https://github.com/DronMDF/zond/issues/17), [#18](https://github.com/DronMDF/zond/issues/18), [#19](https://github.com/DronMDF/zond/issues/19), [#20](https://github.com/DronMDF/zond/issues/20) are still not solved.

**Comment by 0pdd** [comment]
@DronMDF 3 puzzles [#18](https://github.com/DronMDF/zond/issues/18), [#19](https://github.com/DronMDF/zond/issues/19), [#20](https://github.com/DronMDF/zond/issues/20) are still not solved; solved: [#17](https://github.com/DronMDF/zond/issues/17).

**Comment by 0pdd** [comment]
@DronMDF 5 puzzles [#19](https://github.com/DronMDF/zond/issues/19), [#33](https://github.com/DronMDF/zond/issues/33), [#34](https://github.com/DronMDF/zond/issues/34), [#38](https://github.com/DronMDF/zond/issues/38), [#39](https://github.com/DronMDF/zond/issues/39) are still not solved; solved: [#17](https://github.com/DronMDF/zond/issues/17), [#18](https://github.com/DronMDF/zond/issues/18), [#20](https://github.com/DronMDF/zond/issues/20), [#35](https://github.com/DronMDF/zond/issues/35).

**Comment by 0pdd** [comment]
@DronMDF 5 puzzles [#19](https://github.com/DronMDF/zond/issues/19), [#33](https://github.com/DronMDF/zond/issues/33), [#34](https://github.com/DronMDF/zond/issues/34), [#38](https://github.com/DronMDF/zond/issues/38), [#42](https://github.com/DronMDF/zond/issues/42) are still not solved; solved: [#17](https://github.com/DronMDF/zond/issues/17), [#18](https://github.com/DronMDF/zond/issues/18), [#20](https://github.com/DronMDF/zond/issues/20), [#35](https://github.com/DronMDF/zond/issues/35), [#39](https://github.com/DronMDF/zond/issues/39).

**Comment by 0pdd** [comment]
@DronMDF 4 puzzles [#19](https://github.com/DronMDF/zond/issues/19), [#33](https://github.com/DronMDF/zond/issues/33), [#34](https://github.com/DronMDF/zond/issues/34), [#42](https://github.com/DronMDF/zond/issues/42) are still not solved; solved: [#17](https://github.com/DronMDF/zond/issues/17), [#18](https://github.com/DronMDF/zond/issues/18), [#20](https://github.com/DronMDF/zond/issues/20), [#35](https://github.com/DronMDF/zond/issues/35), [#38](https://github.com/DronMDF/zond/issues/38), [#39](https://github.com/DronMDF/zond/issues/39).

**Comment by 0pdd** [comment]
@DronMDF 3 puzzles [#19](https://github.com/DronMDF/zond/issues/19), [#33](https://github.com/DronMDF/zond/issues/33), [#34](https://github.com/DronMDF/zond/issues/34) are still not solved; solved: [#17](https://github.com/DronMDF/zond/issues/17), [#18](https://github.com/DronMDF/zond/issues/18), [#20](https://github.com/DronMDF/zond/issues/20), [#35](https://github.com/DronMDF/zond/issues/35), [#38](https://github.com/DronMDF/zond/issues/38), [#39](https://github.com/DronMDF/zond/issues/39), [#42](https://github.com/DronMDF/zond/issues/42).
