### ISSUE TITLE
Options.h:12-13: Option should have method for string/int...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/zond#152]
The puzzle `142-cf7d6cca` from #142 has to be resolved: 

https://github.com/DronMDF/zond/blob/965340de08e9772ce089c0e063a07e359e888877/http/Options.h#L12-L13

The puzzle was created by Andrey Valyaev on 10-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by DronMDF** [comment]
maybe use OptionsValue with conversion to string/int/bool?

**Comment by 0pdd** [comment]
The puzzle `142-cf7d6cca` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#156](https://github.com/DronMDF/zond/issues/156) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#159](https://github.com/DronMDF/zond/issues/159) is still not solved; solved: [#156](https://github.com/DronMDF/zond/issues/156).
