### ISSUE TITLE
Server mining

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/zond#154]
If enabled - server use n thread for mining scores

--mining-threads 2

By default - 0, mining is disabled.

**Comment by DronMDF** [comment]
Каждый тред майнит самостоятельно, и для этого у него есть ссылка на Scores (вообще ссылки на Scores не хватит, потому, что Scores не позволяет себя расширять, или предусмотреть там отдельный интерфейс расширения, всеравно нужно лочить).
Scores нужно лочить...

Выбраем из Scores первую, которая моложе, чем score-miningtime, и ее майним.
Интервалы можно сделать меньше... 5 секунд...

Пока довольно неоднозначно.

**Comment by 0pdd** [comment]
@DronMDF the puzzle [#163](https://github.com/DronMDF/zond/issues/163) is still not solved.

**Comment by 0pdd** [comment]
@DronMDF the only puzzle [#163](https://github.com/DronMDF/zond/issues/163) is solved here.
