### ISSUE TITLE
ScoreHashString.h:13-14: ScoreValid should check strength...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/zond#173]
The puzzle `170-c3af4a17` from #170 has to be resolved: 

https://github.com/DronMDF/zond/blob/366b8a9f6a20bf5b4047ba56e4ab230a5af19703/http/ScoreHashString.h#L13-L14

The puzzle was created by Andrey Valyaev on 16-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by DronMDF** [comment]
Need to introduce HashString whoes calculate Hash as string...

**Comment by 0pdd** [comment]
The puzzle `170-c3af4a17` has disappeared from the source code, that's why I closed this issue.
