### ISSUE TITLE
Extend GetInfoEntry with need fields

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/zond#185]
for standart zold server interaction

**Comment by DronMDF** [comment]
Get info from this link
https://github.com/zold-io/zold.github.io/blob/ccb602ea8e586b518812b170e0e8c0232748fcda/js/health.js#L175

**Comment by 0pdd** [comment]
@DronMDF 5 puzzles [#194](https://github.com/DronMDF/zond/issues/194), [#195](https://github.com/DronMDF/zond/issues/195), [#196](https://github.com/DronMDF/zond/issues/196), [#197](https://github.com/DronMDF/zond/issues/197), [#198](https://github.com/DronMDF/zond/issues/198) are still not solved.

**Comment by 0pdd** [comment]
@DronMDF 4 puzzles [#194](https://github.com/DronMDF/zond/issues/194), [#195](https://github.com/DronMDF/zond/issues/195), [#196](https://github.com/DronMDF/zond/issues/196), [#198](https://github.com/DronMDF/zond/issues/198) are still not solved; solved: [#197](https://github.com/DronMDF/zond/issues/197).

**Comment by 0pdd** [comment]
@DronMDF 3 puzzles [#194](https://github.com/DronMDF/zond/issues/194), [#195](https://github.com/DronMDF/zond/issues/195), [#196](https://github.com/DronMDF/zond/issues/196) are still not solved; solved: [#197](https://github.com/DronMDF/zond/issues/197), [#198](https://github.com/DronMDF/zond/issues/198).

**Comment by 0pdd** [comment]
@DronMDF 3 puzzles [#195](https://github.com/DronMDF/zond/issues/195), [#196](https://github.com/DronMDF/zond/issues/196), [#234](https://github.com/DronMDF/zond/issues/234) are still not solved; solved: [#194](https://github.com/DronMDF/zond/issues/194), [#197](https://github.com/DronMDF/zond/issues/197), [#198](https://github.com/DronMDF/zond/issues/198).

**Comment by 0pdd** [comment]
@DronMDF 2 puzzles [#195](https://github.com/DronMDF/zond/issues/195), [#196](https://github.com/DronMDF/zond/issues/196) are still not solved; solved: [#194](https://github.com/DronMDF/zond/issues/194), [#197](https://github.com/DronMDF/zond/issues/197), [#198](https://github.com/DronMDF/zond/issues/198), [#234](https://github.com/DronMDF/zond/issues/234).
