### ISSUE TITLE
Deploy procedure over ansible

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/zond#201]

**Comment by DronMDF** [comment]
Idea "prebuild modules and copy it to server" was failed.
Old kernel not want to run my binaries.

**Comment by 0pdd** [comment]
@DronMDF the puzzle [#225](https://github.com/DronMDF/zond/issues/225) is still not solved.

**Comment by 0pdd** [comment]
@DronMDF the puzzle [#227](https://github.com/DronMDF/zond/issues/227) is still not solved; solved: [#225](https://github.com/DronMDF/zond/issues/225).

**Comment by 0pdd** [comment]
@DronMDF the puzzle [#229](https://github.com/DronMDF/zond/issues/229) is still not solved; solved: [#225](https://github.com/DronMDF/zond/issues/225), [#227](https://github.com/DronMDF/zond/issues/227).
