### ISSUE TITLE
Score string format

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/zond#230]
Score format from zold-score repo

 # Parses it back from the text generated by <tt>to_s</tt>.
    def self.parse(text)
      raise 'Can\'t parse nil' if text.nil?
      parts = text.split(' ', 7)
      raise 'Invalid score, not enough parts' if parts.length < 6
      Score.new(
        time: Time.at(parts[1].hex),
        host: parts[2],
        port: parts[3].hex,
        invoice: "#{parts[4]}@#{parts[5]}",
        suffixes: parts[6] ? parts[6].split(' ') : [],
        strength: parts[0].to_i
      )
    rescue StandardError => e
      raise CantParse, "#{e.message} in #{text.inspect}"
    end

**Comment by 0pdd** [comment]
@DronMDF the puzzle [#236](https://github.com/DronMDF/zond/issues/236) is still not solved.

**Comment by 0pdd** [comment]
@DronMDF the only puzzle [#236](https://github.com/DronMDF/zond/issues/236) is solved here.
