### ISSUE TITLE
HttpHeader.cpp:16: Get field value from header content

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/zond#39]
The puzzle `35-808023e7` from #35 has to be resolved: 

https://github.com/DronMDF/zond/blob/0b3e5741060d16806f95454de0c6270b3cef1ab5/HttpHeader.cpp#L16-L16

The puzzle was created by Andrey Valyaev on 23-Nov-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by DronMDF** [comment]
Need a default value too...

**Comment by 0pdd** [comment]
The puzzle `35-808023e7` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#42](https://github.com/DronMDF/zond/issues/42) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#42](https://github.com/DronMDF/zond/issues/42) is solved here.
