### ISSUE TITLE
GET /version should return Version string

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/zond#53]

**Comment by 0pdd** [comment]
@DronMDF 2 puzzles [#55](https://github.com/DronMDF/zond/issues/55), [#56](https://github.com/DronMDF/zond/issues/56) are still not solved.

**Comment by 0pdd** [comment]
@DronMDF 4 puzzles [#56](https://github.com/DronMDF/zond/issues/56), [#59](https://github.com/DronMDF/zond/issues/59), [#60](https://github.com/DronMDF/zond/issues/60), [#61](https://github.com/DronMDF/zond/issues/61) are still not solved; solved: [#55](https://github.com/DronMDF/zond/issues/55).

**Comment by 0pdd** [comment]
@DronMDF 3 puzzles [#56](https://github.com/DronMDF/zond/issues/56), [#59](https://github.com/DronMDF/zond/issues/59), [#60](https://github.com/DronMDF/zond/issues/60) are still not solved; solved: [#55](https://github.com/DronMDF/zond/issues/55), [#61](https://github.com/DronMDF/zond/issues/61).

**Comment by 0pdd** [comment]
@DronMDF 2 puzzles [#56](https://github.com/DronMDF/zond/issues/56), [#59](https://github.com/DronMDF/zond/issues/59) are still not solved; solved: [#55](https://github.com/DronMDF/zond/issues/55), [#60](https://github.com/DronMDF/zond/issues/60), [#61](https://github.com/DronMDF/zond/issues/61).

**Comment by 0pdd** [comment]
@DronMDF 4 puzzles [#56](https://github.com/DronMDF/zond/issues/56), [#69](https://github.com/DronMDF/zond/issues/69), [#70](https://github.com/DronMDF/zond/issues/70), [#71](https://github.com/DronMDF/zond/issues/71) are still not solved; solved: [#55](https://github.com/DronMDF/zond/issues/55), [#59](https://github.com/DronMDF/zond/issues/59), [#60](https://github.com/DronMDF/zond/issues/60), [#61](https://github.com/DronMDF/zond/issues/61).

**Comment by 0pdd** [comment]
@DronMDF 3 puzzles [#56](https://github.com/DronMDF/zond/issues/56), [#70](https://github.com/DronMDF/zond/issues/70), [#71](https://github.com/DronMDF/zond/issues/71) are still not solved; solved: [#55](https://github.com/DronMDF/zond/issues/55), [#59](https://github.com/DronMDF/zond/issues/59), [#60](https://github.com/DronMDF/zond/issues/60), [#61](https://github.com/DronMDF/zond/issues/61), [#69](https://github.com/DronMDF/zond/issues/69).

**Comment by 0pdd** [comment]
@DronMDF 2 puzzles [#56](https://github.com/DronMDF/zond/issues/56), [#71](https://github.com/DronMDF/zond/issues/71) are still not solved; solved: [#55](https://github.com/DronMDF/zond/issues/55), [#59](https://github.com/DronMDF/zond/issues/59), [#60](https://github.com/DronMDF/zond/issues/60), [#61](https://github.com/DronMDF/zond/issues/61), [#69](https://github.com/DronMDF/zond/issues/69), [#70](https://github.com/DronMDF/zond/issues/70).

**Comment by 0pdd** [comment]
@DronMDF 2 puzzles [#212](https://github.com/DronMDF/zond/issues/212), [#71](https://github.com/DronMDF/zond/issues/71) are still not solved; solved: [#55](https://github.com/DronMDF/zond/issues/55), [#56](https://github.com/DronMDF/zond/issues/56), [#59](https://github.com/DronMDF/zond/issues/59), [#60](https://github.com/DronMDF/zond/issues/60), [#61](https://github.com/DronMDF/zond/issues/61), [#69](https://github.com/DronMDF/zond/issues/69), [#70](https://github.com/DronMDF/zond/issues/70).

**Comment by 0pdd** [comment]
@DronMDF the puzzle [#71](https://github.com/DronMDF/zond/issues/71) is still not solved; solved: [#212](https://github.com/DronMDF/zond/issues/212), [#55](https://github.com/DronMDF/zond/issues/55), [#56](https://github.com/DronMDF/zond/issues/56), [#59](https://github.com/DronMDF/zond/issues/59), [#60](https://github.com/DronMDF/zond/issues/60), [#61](https://github.com/DronMDF/zond/issues/61), [#69](https://github.com/DronMDF/zond/issues/69), [#70](https://github.com/DronMDF/zond/issues/70).
