### ISSUE TITLE
GetInfoEntry.cpp:15: Add Score to Info response

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/zond#91]
The puzzle `82-86cc26c2` from #82 has to be resolved: 

https://github.com/DronMDF/zond/blob/7f1b4e894093bcc39fbddf89850d81ed83c8986b/http/GetInfoEntry.cpp#L15-L15

The puzzle was created by Andrey Valyaev on 09-Dec-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by DronMDF** [comment]
Довольно много вариантов, стоит повыбирать
https://github.com/miloyip/nativejson-benchmark

**Comment by 0pdd** [comment]
The puzzle `82-86cc26c2` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#182](https://github.com/DronMDF/zond/issues/182) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#184](https://github.com/DronMDF/zond/issues/184) is still not solved; solved: [#182](https://github.com/DronMDF/zond/issues/182).
