### ISSUE TITLE
Json support library

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/zond#98]
https://github.com/nlohmann/json

**Comment by 0pdd** [comment]
@DronMDF the puzzle [#100](https://github.com/DronMDF/zond/issues/100) is still not solved.

**Comment by 0pdd** [comment]
@DronMDF 2 puzzles [#100](https://github.com/DronMDF/zond/issues/100), [#102](https://github.com/DronMDF/zond/issues/102) are still not solved.

**Comment by 0pdd** [comment]
@DronMDF 2 puzzles [#102](https://github.com/DronMDF/zond/issues/102), [#104](https://github.com/DronMDF/zond/issues/104) are still not solved; solved: [#100](https://github.com/DronMDF/zond/issues/100).

**Comment by 0pdd** [comment]
@DronMDF the puzzle [#104](https://github.com/DronMDF/zond/issues/104) is still not solved; solved: [#100](https://github.com/DronMDF/zond/issues/100), [#102](https://github.com/DronMDF/zond/issues/102).

**Comment by 0pdd** [comment]
@DronMDF all 3 puzzles are solved here: [#100](https://github.com/DronMDF/zond/issues/100), [#102](https://github.com/DronMDF/zond/issues/102), [#104](https://github.com/DronMDF/zond/issues/104).
